CREATE TABLE bank_transactions (
    trans_date_trans_time TIMESTAMP,
    cc_num BIGINT,
    merchant VARCHAR(255),
    category VARCHAR(100),
    amt NUMERIC(10,2),
    first VARCHAR(100),
    last VARCHAR(100),
    gender CHAR(1),
    street VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(10),
    zip INT,
    lat NUMERIC(10,6),
    "long" NUMERIC(10,6),
    city_pop BIGINT,
    job VARCHAR(255),
    dob DATE,
    trans_num VARCHAR(100),
    unix_time BIGINT,
    merch_lat NUMERIC(10,6),
    merch_long NUMERIC(10,6),
    is_fraud INT,
    merch_zipcode BIGINT
);
